### ISSUE TITLE
QUESTION: How do I turn on?

### ISSUE THREAD

**Issue by JE90** [josh-seagrave/EasyCPDLC#14]
How  do I turn on this program?

**Comment by josh-seagrave** [comment]
Hi,

Apologies, the documentation is still very WIP.

After installing EasyCPDLC simply run the .exe file. On first startup, EASYCPDLC will ask for your VATSIM CID and Hoppie code. Once those are submitted, you can then press the "Connect" button to synchronise your flight data, then you are able to send and receive messages through the ATC and Telex menus.

Hope this helps.

**Comment by JE90** [comment]
can be run from a different pc from the SIM one?

**Comment by josh-seagrave** [comment]
In theory, yes. There's absolutely 0 sim integration, so it doesn't need to be on the same PC, or even the same network

**Comment by JE90** [comment]
I download the wrong file, now is working
