### ISSUE TITLE
Recieving a logoff does not do anything

### ISSUE THREAD

**Issue by Adrian2k** [josh-seagrave/EasyCPDLC#17]
![image](https://user-images.githubusercontent.com/35482228/143735612-7912cc39-38a3-4138-bb2d-3706fb8ada7e.png)

I would imaging when recieving a logoff, it should actually logoff without needing me to do it? As you can see, current ATC unit is still LOVE and opening the ATC menu I do only have logoff as an option, no logon.

**Comment by josh-seagrave** [comment]
Hi Adrian,

Yes, you are correct, that should have terminated the CPDLC connection. I'll look into what went wrong today.
Thanks for letting me know
