### ISSUE TITLE
Disconnect button says DISCONNEC

### ISSUE THREAD

**Issue by SeaHawkGaming** [josh-seagrave/EasyCPDLC#18]
Well, pretty self explanatory this one :P

**Comment by josh-seagrave** [comment]
Huh... Okay! I'll have a look, I might have made a formatting mistake!

**Comment by SeaHawkGaming** [comment]
Might be something different, just noticed another one, in the ATC menu REQUEST is also missing the T in the end, as in the screenshot attached
![image](https://user-images.githubusercontent.com/28776198/144106465-fd220cd1-4532-4157-be23-33dc09aff033.png)

**Comment by josh-seagrave** [comment]
> Might be something different, just noticed another one, in the ATC menu REQUEST is also missing the T in the end, as in the screenshot attached ![image](https://user-images.githubusercontent.com/28776198/144106465-fd220cd1-4532-4157-be23-33dc09aff033.png) For reference, Win 10 pro 64, no additional changes

Thanks, it's the same root cause. Seems to only happen with some people and not with others, I have no idea why at the moment but I'm looking into it.

Hoping to have a fix pushed in the next day or two, keep an eye out!

**Comment by josh-seagrave** [comment]
Think I might have just encountered the issue by comparing and contrasting your screenshot with how EasyCPDLC looks on my screen. I think I included the wrong font family in the previous build, and it's therefore not displaying correctly. I'll do some testing to see if I can replicate this
