### ISSUE TITLE
Cannot enter name into Simbrief input

### ISSUE THREAD

**Issue by GiacomoLaw** [josh-seagrave/EasyCPDLC#25]
Hey there, can't enter my SB username. Simply doesn't type anything.

Thanks for the great app

**Comment by josh-seagrave** [comment]
Hi there!

The program uses your SimBrief _User ID_, not _username_. Subsequently, the box only allows numbers to be entered.

There are instructions in the [changelog](https://github.com/josh-seagrave/EasyCPDLC/releases/tag/cpdlc0.1.2.0) showing how this can be found.

Hope this helps

**Comment by GiacomoLaw** [comment]
Whoops, my mistake - thank you
