### ISSUE TITLE
Feature request: remember dialog positions

### ISSUE THREAD

**Issue by droesen** [josh-seagrave/EasyCPDLC#26]
SSIA, it would be good to remember the dialog box positions so dialogs don't open always at a default position (which is in my case monitor #1 far top-left, and I would like them on monitor #3 top-center... far away). Thanks for consideration!

**Comment by josh-seagrave** [comment]
> SSIA, it would be good to remember the dialog box positions so dialogs don't open always at a default position (which is in my case monitor #1 far top-left, and I would like them on monitor #3 top-center... far away). Thanks for consideration!

This is a great idea, I'll have a look at implementing this
