### ISSUE TITLE
Unable install

### ISSUE THREAD

**Issue by RudiZhang** [josh-seagrave/EasyCPDLC#28]
Hi, I'm glad you released Beta 0.1.3.0. But I can't open EasyCPDLCInstaller.exe, there seems to be something wrong with the package? Can you check it?

**Comment by josh-seagrave** [comment]
> Hi, I'm glad you released Beta 0.1.3.0. But I can't open EasyCPDLCInstaller.exe, there seems to be something wrong with the package? Can you check it?

Hi! I'll double check it! I ran the installer on my machine and it worked okay. Do you get any error message?

**Comment by RudiZhang** [comment]
> > Hi, I'm glad you released Beta 0.1.3.0. But I can't open EasyCPDLCInstaller.exe, there seems to be something wrong with the package? Can you check it?
> 
> Hi! I'll double check it! I ran the installer on my machine and it worked okay. Do you get any error message?

no nothing, it just disappear

**Comment by josh-seagrave** [comment]
> > > Hi, I'm glad you released Beta 0.1.3.0. But I can't open EasyCPDLCInstaller.exe, there seems to be something wrong with the package? Can you check it?
> > 
> > Hi! I'll double check it! I ran the installer on my machine and it worked okay. Do you get any error message?
> 
> no nothing, it just disappear

Okay, that's interesting. I'll rebuild the installer and try it again. It will have to wait until tomorrow as it's 4am but I'll let you know when it's done.

**Comment by herver** [comment]
Hi there,

I have the same problem, the installer closes right away.

One thing I noticed: version 0.1.2.0 installer was 12MB in size whereas 0.1.3.0 is only ~2MB (not sure it's related though... )

Also, (at least for me: I can file a separate bug if needed): with current installed version (0.1.2.0), it closes automatically if I press "No" when prompted to upgrade, making the software unusable as the update is broken 😄

**Comment by josh-seagrave** [comment]
> Hi there,
> 
> I have the same problem, the installer closes right away.
> 
> One thing I noticed: version 0.1.2.0 installer was 12MB in size whereas 0.1.3.0 is only ~2MB (not sure it's related though... )
> 
> Also, (at least for me: I can file a separate bug if needed): with current installed version (0.1.2.0), it closes automatically if I press "No" when prompted to upgrade, making the software unusable as the update is broken 😄 

Damn and blast, I forgot I did that.

Right, I'm up for the day so I'll get a new build sorted. Watch this space!

**Comment by josh-seagrave** [comment]
@herver @RudiZhang Thanks for your patience gents. Turned out I built the installer with a .cab file, instead of everything being contained within the .exe! Not my brightest moment. I've rebuilt the installer and edited the release, so that should now be correct!

Thanks for pointing it out

**Comment by herver** [comment]
Thank you very much for the quick action !

I did a fresh install and it works as expected now... is there somewhere we can see the current version we're running, I couldn't find it in the `?` nor the settings.

Cheers

**Comment by diibify** [comment]
> A more recent version of EasyCPDLC is alredy installed...

I am not able to upgrade for now (a reinstall should work).

**Comment by josh-seagrave** [comment]
> Thank you very much for the quick action !
> 
> I did a fresh install and it works as expected now... is there somewhere we can see the current version we're running, I couldn't find it in the `?` nor the settings.
> 
> Cheers

Besides checking the properties of the .exe, no. That's a good idea though, I'll make sure that's included in the next build.

**Comment by josh-seagrave** [comment]
> > A more recent version of EasyCPDLC is alredy installed...
> 
> I am not able to upgrade for now (a reinstall should work).

A reinstall should work fine. It might throw a hissyfit if you don't reinstall because of the way I rebuilt the exe

**Comment by RudiZhang** [comment]
It works! Thank you!

**Comment by Royalclass** [comment]
Hi,  I am unable to run easycpdlc. There is an .exe file inside a Zip file which is in its turn in the parent Zip file. After extracting the zip file with the .exe file, nothing happens, apart from a window warning for possible viruses.
