### ISSUE TITLE
something missing not loading correct 

### ISSUE THREAD

**Issue by laurenswa** [josh-seagrave/EasyCPDLC#30]
I just reinstalled v0.13 
but i think that there is somthing wrong with the installer.

maybe you can help
![Naamloos](https://user-images.githubusercontent.com/98109364/150373135-146946b6-e5af-46b6-b985-65b54956f113.png)
.

**Comment by josh-seagrave** [comment]
> I just reinstalled v0.13 
> but i think that there is somthing wrong with the installer.
> 
> maybe you can help
> ![Naamloos](https://user-images.githubusercontent.com/98109364/150373135-146946b6-e5af-46b6-b985-65b54956f113.png)
> .

Let me look, hold on

**Comment by josh-seagrave** [comment]
> I just reinstalled v0.13 
> but i think that there is somthing wrong with the installer.
> 
> maybe you can help
> ![Naamloos](https://user-images.githubusercontent.com/98109364/150373135-146946b6-e5af-46b6-b985-65b54956f113.png)
> .

Everything seems to be okay with my PC, it installed without issue. Could you try a complete reinstall of EasyCPDLC, and send me a copy of the EasyCPDLCLog.txt please?

**Comment by laurenswa** [comment]
i will give me a sec

**Comment by laurenswa** [comment]
still the same.

2022-01-20 20:57:06.1072|INFO|EasyCPDLC.MainForm|Logging initialised, beginning setup
2022-01-20 20:57:06.3722|INFO|EasyCPDLC.MainForm|Login menu initialised
2022-01-20 20:57:06.3722|INFO|EasyCPDLC.MainForm|Login Form Displayed
2022-01-20 20:57:07.6194|INFO|EasyCPDLC.MainForm|REMEMBER ME: TRUE. REGISTRY SET.
2022-01-20 20:57:07.6194|INFO|EasyCPDLC.MainForm|Setup Complete.
2022-01-20 20:57:07.6194|INFO|EasyCPDLC.MainForm|Setup completed successfully
2022-01-20 20:57:10.9874|DEBUG|EasyCPDLC.MainForm|VATSIM Data Retrieved and Parsed
2022-01-20 20:57:10.9904|DEBUG|EasyCPDLC.MainForm|Writing message: VATSIM DATA RETRIEVED FOR KLM689
2022-01-20 20:57:11.0124|DEBUG|EasyCPDLC.MainForm|Attempting to poll Hoppie for new messages
2022-01-20 20:57:11.4663|DEBUG|EasyCPDLC.MainForm|Writing message: ERROR RETRIEVING SIMBRIEF DATA. POSITION REPORTING WILL REVERT TO BASIC FUNCTIONALITY
2022-01-20 20:57:11.4752|DEBUG|EasyCPDLC.MainForm|PACKET SENT: NONE | poll |  | True | True
2022-01-20 20:57:11.4752|DEBUG|EasyCPDLC.MainForm|RECEIVED: ok

**Comment by josh-seagrave** [comment]
> still the same.
> 
> 2022-01-20 20:57:06.1072|INFO|EasyCPDLC.MainForm|Logging initialised, beginning setup 2022-01-20 20:57:06.3722|INFO|EasyCPDLC.MainForm|Login menu initialised 2022-01-20 20:57:06.3722|INFO|EasyCPDLC.MainForm|Login Form Displayed 2022-01-20 20:57:07.6194|INFO|EasyCPDLC.MainForm|REMEMBER ME: TRUE. REGISTRY SET. 2022-01-20 20:57:07.6194|INFO|EasyCPDLC.MainForm|Setup Complete. 2022-01-20 20:57:07.6194|INFO|EasyCPDLC.MainForm|Setup completed successfully 2022-01-20 20:57:10.9874|DEBUG|EasyCPDLC.MainForm|VATSIM Data Retrieved and Parsed 2022-01-20 20:57:10.9904|DEBUG|EasyCPDLC.MainForm|Writing message: VATSIM DATA RETRIEVED FOR KLM689 2022-01-20 20:57:11.0124|DEBUG|EasyCPDLC.MainForm|Attempting to poll Hoppie for new messages 2022-01-20 20:57:11.4663|DEBUG|EasyCPDLC.MainForm|Writing message: ERROR RETRIEVING SIMBRIEF DATA. POSITION REPORTING WILL REVERT TO BASIC FUNCTIONALITY 2022-01-20 20:57:11.4752|DEBUG|EasyCPDLC.MainForm|PACKET SENT: NONE | poll | | True | True 2022-01-20 20:57:11.4752|DEBUG|EasyCPDLC.MainForm|RECEIVED: ok

Okay. Thanks for letting me know, I'll look into it and see if I can work something out. Sorry it's giving you trouble. Is it just that page that shows no labels or is it all of them that aren't displaying correctly?

**Comment by laurenswa** [comment]
np. there is noting showing wen I try to connect. and If i you to settings only the tabs are visible
![Naamloos](https://user-images.githubusercontent.com/98109364/150416370-687015df-0418-4774-a269-f591c4287d55.png)
.

**Comment by josh-seagrave** [comment]
> np. there is noting showing wen I try to connect. and If i you to settings only the tabs are visible ![Naamloos](https://user-images.githubusercontent.com/98109364/150416370-687015df-0418-4774-a269-f591c4287d55.png) .

That's really, really bizarre. I'll look into it tonight.

**Comment by laurenswa** [comment]
yeah I know. V0.0.12 worked perfect, keep me posted ;)

**Comment by josh-seagrave** [comment]
> np. there is noting showing wen I try to connect. and If i you to settings only the tabs are visible ![Naamloos](https://user-images.githubusercontent.com/98109364/150416370-687015df-0418-4774-a269-f591c4287d55.png) .

Looking at the screenshots, it looks like the fonts that EasyCPDLC needs are missing, somehow. Could you please download this .zip and install the 3 fonts contained inside, and see if that fixes the issue?

[EasyCPDLCFonts.zip](https://github.com/josh-seagrave/EasyCPDLC/files/7908416/EasyCPDLCFonts.zip)

**Comment by laurenswa** [comment]
do i need to put the 3 files in the easyCPDLC folder?

**Comment by josh-seagrave** [comment]
> do i need to put the 3 files in the easyCPDLC folder?

Nope, just extract them somewhere convenient, double click each one and it should give you the option to install the font :)

**Comment by laurenswa** [comment]
Nope still the same

**Comment by josh-seagrave** [comment]
> Nope still the same

Okay, I'll keep digging. I asked a friend to install it to make sure I wasn't going mad, he had no issues either. Bear with me.

**Comment by laurenswa** [comment]
shout it help if i restart my pc ?

**Comment by josh-seagrave** [comment]
> shout it help if i restart my pc ?

it can't hurt, I suppose

**Comment by laurenswa** [comment]
heey just did a fly and now it works perfect thx for the help. love your product ;)

**Comment by josh-seagrave** [comment]
> heey just did a fly and now it works perfect thx for the help. love your product ;)

Glad it's working! I'm assuming the restart fixed it?
