### ISSUE TITLE
Attempting to connect creates a "VATSIM: ERROR" message

### ISSUE THREAD

**Issue by mnurick** [josh-seagrave/EasyCPDLC#38]
Several users on the CTP Discord are reporting issues when attempting to connect after the latest update: https://discord.com/channels/757323458609938513/936025932735578162/959423991804739674

![image](https://user-images.githubusercontent.com/3536144/161273045-7855c71d-81f7-478e-83ba-99497bac6486.png)

We've confirmed hoppie, vatsim, and simbrief IDs are all populated. Application is running in administrator mode.

**Comment by mnurick** [comment]
Filing a flight plan on vatsim seems to correct the issue.

**Comment by josh-seagrave** [comment]
Hi @mnurick ,

sorry about that, I changed the format for the error messages but I think I might have condensed them a bit *too* much.
A flight plan is required so that EasyCPDLC can get all the details it needs :)

Hope this clears things up,

Joshua

**Comment by mnurick** [comment]
Thanks for following up! Appreciate all the work you've put into this.
