### ISSUE TITLE
Previous version installs, latest starts but never appears on screen

### ISSUE THREAD

**Issue by adamparnell** [josh-seagrave/EasyCPDLC#40]
Hi Josh

The latest installer never appears when installing, both as an administrator or not but the previous version happily runs

**Comment by josh-seagrave** [comment]
Hi Adam,

The latest version isn't an installer, it's a straight replacement for the .exe,as per the install instructions on the release.

`INSTALL INSTRUCTIONS:
Replace the EasyCPDLC.exe in your EasyCPDLC root folder with this version.`
