### ISSUE TITLE
Unable install

### ISSUE THREAD

**Issue by RudiZhang** [josh-seagrave/EasyCPDLC#41]
Hi,
new beta cannot be install again

**Comment by josh-seagrave** [comment]
The latest release is a HOTFIX. It is not a full installation.

To install from clean, install 0.1.5.0 and then replace the .exe with the 0.1.5.6 exe.

![Screenshot_20220504-125019_GitHub.jpg](https://user-images.githubusercontent.com/24682725/166675756-6b6d3416-4ba9-46e8-bf43-9423aff69e7d.jpg)
