### ISSUE TITLE
Repeatedly asking to download missing framworks for .NET

### ISSUE THREAD

**Issue by ScriptedChapter** [josh-seagrave/EasyCPDLC#72]
When I try to run the program it asks me to download frameworks, and I click OK, then it justs repeats that, clicks ok, prompt goes away, but when I try to run it again it asks me the same thing. I have downloaded .NET 8.0 manually.

**Comment by edutufano** [comment]
Hi! Iam having the same here, did you fix it? Please, i already installed 8.0

**Comment by ScriptedChapter** [comment]
> Hi! Iam having the same here, did you fix it? Please, i already installed 8.0

Hello! Yes. I installed this application called HandBrake. (Not related to anything with easycpdlc) After that it worked. Idk how it works but I suppose the handbrake application installs missing frameworks automatically when you run it without netframeworks. You can also follow this vid: https://youtu.be/Pe4z8ToqplY?si=wBorrSjtvnLbLku8

Just download and run the application then close it then try to launch easycpdlc then it should work.
