### ISSUE TITLE
VATSIM: ERROR. WAIT 60 SECONDS AND RETRY

### ISSUE THREAD

**Issue by acarrasquillo** [josh-seagrave/EasyCPDLC#78]
Hi @quassbutreally I keep getting the message error below while trying to click connect. I have filed the flight plan using simbrief and the simbrief vatsim prefile button. I'm unable to troubleshoot what is happening. I'm also able to connect fine on vPilot client on vatsim. Any tips you can think of? Thanks for the assistance.

![image](https://github.com/user-attachments/assets/199a69e8-b0b7-4e37-8c81-64e485adacef)

**Comment by acarrasquillo** [comment]
Ok, looking at the code is looking for my pilot ID on https://data.vatsim.net/v3/vatsim-data.json and for some reason I'm not on that list. I show up but under controllers instead of under pilots

**Comment by acarrasquillo** [comment]
I think the issue is that I can't connect as an observer

![image](https://github.com/user-attachments/assets/c45210e1-7da8-4411-b799-978c4ca7e380)

**Comment by acarrasquillo** [comment]
Everything is good now I'll continue testing

![image](https://github.com/user-attachments/assets/a885d686-bbf7-46c3-9a90-322ebb366225)

**Comment by My4rt** [comment]
@acarrasquillo I have the same problem, how were you able to solve it?
